#! /bin/bash
#mount /windows/u &
#mount /windows/w &

cd /home/defender/.conky/

for A in $(pidof conky)
do
    kill $A
done

conky -c ~/.conky/coweb --alignment=top_left &
conky -c ~/.conky/conk --alignment=top_left &

exit 0